### ISSUE TITLE
Fatal error on D:\xampp\htdocs\bWAPP\connect.php on line 23

### ISSUE THREAD

**Issue by Ri1a** [theand-fork/bwapp-code#2]
So, I've recently installed bWAPP. The first bugs worked fine, but when I want to start an SQL-injection attack it throws me this error:

```
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in D:\xampp\htdocs\bWAPP\connect.php:23 Stack trace: #0 D:\xampp\htdocs\bWAPP\sqli_1.php(23): include() #1 {main} thrown in D:\xampp\htdocs\bWAPP\connect.php on line 23
```

This is the line in the connect.php that throws an error:

```php
// Connects to the server
$link = mysql_connect($server, $username, $password);
```
I run bWAPP locally, why should it connect to a server? Any ideas?

**Comment by Ri1a** [comment]
Tried it again on linux and it worked fine now.

**Comment by w3bd3m0n1337** [comment]
Its not working on windows 10 same issue.

**Comment by lazyboyy** [comment]
this code will help to bypass that error, just paste below code in connect.php file. ask chatgpt for more errors. Happy Hacking :)

```

<?php

/*

bWAPP, or a buggy web application, is a free and open source deliberately insecure web application.
It helps security enthusiasts, developers, and students to discover and prevent web vulnerabilities.
bWAPP covers all major known web vulnerabilities, including all risks from the OWASP Top 10 project!
It is for security-testing and educational purposes only.

Enjoy!

Malik Mesellem
Twitter: @MME_IT

bWAPP is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License (http://creativecommons.org/licenses/by-nc-nd/4.0/). Copyright © 2014 MME BVBA. All rights reserved.

*/

// Connection settings
include("config.inc.php");

// Connects to the server
$conn = mysqli_connect($server, $username, $password, $database);

// Checks the connection
if (!$conn) {
    die("Could not connect to the server: " . mysqli_connect_error());
}

// No need to select the database separately in mysqli

// Commenting out mysql_close as it's not necessary in mysqli
// mysqli_close($conn);

?>
```

**Comment by lazyboyy** [comment]
<?php

/*

bWAPP, or a buggy web application, is a free and open source deliberately insecure web application.
It helps security enthusiasts, developers, and students to discover and prevent web vulnerabilities.
bWAPP covers all major known web vulnerabilities, including all risks from the OWASP Top 10 project!
It is for security-testing and educational purposes only.

Enjoy!

Malik Mesellem
Twitter: @MME_IT

bWAPP is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License (http://creativecommons.org/licenses/by-nc-nd/4.0/). Copyright © 2014 MME BVBA. All rights reserved.

*/

// Connection settings
include("config.inc.php");

// Connects to the server
$conn = mysqli_connect($server, $username, $password, $database);

// Checks the connection
if (!$conn) {
    die("Could not connect to the server: " . mysqli_connect_error());
}

// No need to select the database separately in mysqli

// Commenting out mysql_close as it's not necessary in mysqli
// mysqli_close($conn);

?>

**Comment by Ankanpaulj123** [comment]
i have new error 

 C:\xampp\htdocs\bWAPP\sqli_13.php

**Comment by PavelVo** [comment]
I fixit like this. 
Add at the beginning of the file connect.php -    include_once("mysql_compat.php");
create new file mysql_compat.php with code 
`<?php
$GLOBALS['mysql_link'] = null;

function mysql_connect($server, $username, $password) {
    $link = mysqli_connect($server, $username, $password);
    if (!$link) {
        return false;
    }
    $GLOBALS['mysql_link'] = $link;
    return $link;
}

function mysql_select_db($database_name, $link = null) {
    if ($link === null) {
        $link = $GLOBALS['mysql_link'];
    }
    return mysqli_select_db($link, $database_name);
}

function mysql_query($query, $link = null) {
    if ($link === null) {
        $link = $GLOBALS['mysql_link'];
    }
    return mysqli_query($link, $query);
}

function mysql_fetch_assoc($result) {
    return mysqli_fetch_assoc($result);
}

function mysql_fetch_array($result, $result_type = MYSQLI_BOTH) {
    return mysqli_fetch_array($result, $result_type);
}

function mysql_num_rows($result) {
    return mysqli_num_rows($result);
}

function mysql_error($link = null) {
    if ($link === null) {
        $link = $GLOBALS['mysql_link'];
    }
    return mysqli_error($link);
}

function mysql_close($link = null) {
    if ($link === null) {
        $link = $GLOBALS['mysql_link'];
    }
    return mysqli_close($link);
}
?>
`
